import { fileURLToPath } from "node:url";
import react from "@vitejs/plugin-react";
import { playwright } from "@vitest/browser-playwright";
import { defineConfig } from "vitest/config";

const path = (relative: string) => fileURLToPath(new URL(relative, import.meta.url));

/**
 * Tests import the workspace packages from their sources, so no build is needed first and coverage
 * is attributed to the files that are actually written.
 */
const packages = {
	"@aegis/contracts": path("packages/contracts/src/index.ts"),
	"@aegis/db": path("packages/db/src/index.ts"),
	"@aegis/email": path("packages/email/src/index.ts"),
};

/**
 * One run for the whole monorepo, with a single merged coverage report. Every workspace keeps its
 * tests in `test/`, next to `src/` and mirroring it, with shared helpers in `test/support/`:
 *
 * - `packages`: contracts, database schema and e-mail templates, in Node.js
 * - `backend`: Fastify, oidc-provider and the services, against a real PostgreSQL
 * - `frontend`: React components, hooks and helpers in a real browser (Chromium through Playwright), `test/browser/`
 * - `frontend-node`: what Next.js runs in Node.js while it exports the pages (`app/`, `i18n/`), `test/node/`
 */
export default defineConfig({
	resolve: { alias: packages },
	test: {
		// The transform diagnostic suggests `fsModuleCache`; measured here, the cache made runs slower,
		// and in CI, where every run starts cold, it cannot help.
		experimental: { diagnostics: { transform: false } },
		projects: [
			{
				test: {
					name: "packages",
					include: ["packages/*/test/**/*.test.{ts,tsx}"],
					environment: "node",
					restoreMocks: true,
				},
			},
			{
				test: {
					name: "backend",
					include: ["apps/backend/test/**/*.test.ts"],
					environment: "node",
					globalSetup: ["apps/backend/test/setup/postgres.ts"],
					restoreMocks: true,
					testTimeout: 30_000,
					hookTimeout: 60_000,
				},
			},
			{
				// Rooted in the frontend, so its dependencies resolve and are pre-bundled before the first test.
				root: path("apps/frontend"),
				plugins: [react()],
				optimizeDeps: {
					// Only some tests import these; bundling them up front saves Vite a reload mid-run.
					include: ["recharts", "qrcode-generator", "cmdk"],
					// Always mocked (`test/setup/browser.tsx`); bundled, their CommonJS interop would hide the mocks' default export.
					exclude: ["next/image", "next/link", "next/navigation"],
				},
				resolve: { alias: { ...packages, "@": path("apps/frontend/src") } },
				test: {
					name: "frontend",
					include: ["test/browser/**/*.test.{ts,tsx}"],
					setupFiles: ["test/setup/browser.tsx"],
					restoreMocks: true,
					// Whole user flows in a real browser, which a busy CI runner slows down, like the backend's.
					testTimeout: 30_000,
					browser: {
						enabled: true,
						headless: true,
						provider: playwright(),
						instances: [{ browser: "chromium" }],
						viewport: { width: 1280, height: 800 },
					},
				},
			},
			{
				plugins: [react()],
				resolve: { alias: { ...packages, "@": path("apps/frontend/src") } },
				test: {
					name: "frontend-node",
					include: ["apps/frontend/test/node/**/*.test.{ts,tsx}"],
					setupFiles: ["apps/frontend/test/setup/node.ts"],
					environment: "node",
					restoreMocks: true,
				},
			},
		],
		coverage: {
			provider: "v8",
			include: ["apps/*/src/**/*.{ts,tsx}", "packages/*/src/**/*.{ts,tsx}"],
			exclude: [
				"**/*.d.ts",
				// Generated by the shadcn/ui CLI and maintained upstream, like `biome.json` excludes them.
				"apps/frontend/src/components/ui/**",
				"apps/frontend/src/hooks/use-mobile.ts",
			],
			// Files with types and re-exports only have nothing to run, so the reports leave them out.
			reporter: [["text", { skipEmpty: true }], ["html", { skipEmpty: true }], "lcov", "json-summary"],
			thresholds: { 100: true },
		},
	},
});
