import { z } from "zod";
import type { IsoDateString } from "./common";
import { emailSchema, newPasswordSchema } from "./identity";

/**
 * Account recovery and e-mail verification. Both flows hand out a single-use link whose token is
 * only ever stored as a hash; the plain token exists in the e-mail and in the link the browser
 * carries back.
 */

/** A token from a verification link: `base64url`, generated by the server. */
export const verificationTokenSchema = z
	.string({ error: "required" })
	.trim()
	.min(1, { error: "required" })
	.max(256, { error: "too_long" })
	.regex(/^[A-Za-z0-9_-]+$/, { error: "invalid" });

/** Redeems or inspects a link from an e-mail. */
export const verificationLinkSchema = z.object({
	token: verificationTokenSchema,
});

export type VerificationLinkRequest = z.infer<typeof verificationLinkSchema>;

export const forgotPasswordSchema = z.object({
	email: emailSchema,
});

export type ForgotPasswordRequest = z.infer<typeof forgotPasswordSchema>;

export const passwordResetConfirmSchema = verificationLinkSchema.extend({
	password: newPasswordSchema,
});

export type PasswordResetConfirmRequest = z.infer<typeof passwordResetConfirmSchema>;

/** What the reset page may show before a new password is entered. */
export interface PasswordResetTokenDto {
	/** Partially hidden, so a leaked link does not reveal the full address. */
	maskedEmail: string;
	displayName: string;
	expiresAt: IsoDateString;
}

/** An e-mail change that has been requested but not confirmed from the new address yet. */
export interface PendingEmailChangeDto {
	/** The address the confirmation was sent to. */
	email: string;
	requestedAt: IsoDateString;
	expiresAt: IsoDateString;
}

export interface EmailChangeConfirmResponse {
	email: string;
}
