"use client";

import { ROLES, type Role, type UserResponse, userCreateSchema } from "@aegis/contracts";
import { Dices, ShieldCheck, UserRound } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useTranslations } from "next-intl";
import { type FormEvent, useState } from "react";
import { toast } from "sonner";
import { CopyField } from "@/components/copy-button";
import { BackLink, Page, PageHeader, Section } from "@/components/dashboard/page";
import { FormField } from "@/components/form-field";
import { PasswordInput } from "@/components/password-input";
import { PasswordStrength } from "@/components/password-strength";
import { StatusMessage } from "@/components/status-message";
import { Button } from "@/components/ui/button";
import { Field, FieldContent, FieldDescription, FieldGroup, FieldLabel } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Spinner } from "@/components/ui/spinner";
import { Switch } from "@/components/ui/switch";
import { useErrorMessage } from "@/hooks/use-error-message";
import { useFormErrors } from "@/hooks/use-form-errors";
import { ApiRequestError, api } from "@/lib/api";
import { cn } from "@/lib/utils";

export const OPTION_CARD =
	"cursor-pointer rounded-xl border bg-card transition-colors hover:bg-muted/40 has-data-[state=checked]:border-primary has-data-[state=checked]:bg-primary/5 has-data-[state=checked]:ring-3 has-data-[state=checked]:ring-primary/15";

/** 18 random bytes as base64url – the same strength as passwords generated by the server. */
export function generatePassword(): string {
	const bytes = crypto.getRandomValues(new Uint8Array(18));
	return btoa(String.fromCharCode(...bytes))
		.replaceAll("+", "-")
		.replaceAll("/", "_")
		.replace(/=+$/, "");
}

const ROLE_ICONS = { user: UserRound, admin: ShieldCheck } as const;

const INITIAL_VALUES = {
	displayName: "",
	email: "",
	password: "",
	role: "user" as Role,
	enabled: true,
	emailVerified: true,
};

export function NewUserPage() {
	const t = useTranslations("newUser");
	const tRoles = useTranslations("roles");
	const tCommon = useTranslations("common");
	const router = useRouter();
	const errorMessage = useErrorMessage();
	const { errors, validate, applyApiError, setFieldError } = useFormErrors();
	const [values, setValues] = useState(INITIAL_VALUES);
	const [generated, setGenerated] = useState<string | null>(null);
	const [submitting, setSubmitting] = useState(false);

	const set = <K extends keyof typeof INITIAL_VALUES>(key: K, value: (typeof INITIAL_VALUES)[K]) =>
		setValues((current) => ({ ...current, [key]: value }));

	function generate() {
		const password = generatePassword();
		setGenerated(password);
		set("password", password);
	}

	async function onSubmit(event: FormEvent<HTMLFormElement>) {
		event.preventDefault();
		const input = validate(userCreateSchema, values);
		if (!input) {
			return;
		}

		setSubmitting(true);
		try {
			const result = await api.post<UserResponse>("/users", input);
			toast.success(t("created", { name: result.user.displayName }));
			router.push(`/users/${result.user.id}`);
		} catch (error) {
			setSubmitting(false);
			if (applyApiError(error)) {
				return;
			}
			if (error instanceof ApiRequestError && error.code === "email_taken") {
				setFieldError("email", "email_taken");
				return;
			}
			toast.error(errorMessage(error));
		}
	}

	return (
		<Page>
			<PageHeader back={<BackLink href="/users">{t("back")}</BackLink>} title={t("title")} description={t("description")} />

			<form onSubmit={onSubmit} noValidate className="flex max-w-3xl flex-col gap-6">
				<Section title={t("role")} description={t("roleDescription")}>
					<div className="flex flex-col gap-4">
						<RadioGroup
							value={values.role}
							onValueChange={(value) => set("role", value as Role)}
							className="grid gap-3 sm:grid-cols-2"
						>
							{ROLES.map((role) => {
								const Icon = ROLE_ICONS[role];
								return (
									<label key={role} htmlFor={`role-${role}`} className={cn(OPTION_CARD, "flex flex-col gap-3 p-4")}>
										<span className="flex items-start justify-between gap-2">
											<span className="flex size-10 items-center justify-center rounded-lg bg-primary/10 text-primary">
												<Icon className="size-5" />
											</span>
											<RadioGroupItem value={role} id={`role-${role}`} />
										</span>
										<span className="flex flex-col gap-1">
											<span className="font-medium">{tRoles(role)}</span>
											<span className="text-sm text-muted-foreground">{t(`roles.${role}`)}</span>
										</span>
									</label>
								);
							})}
						</RadioGroup>
						{values.role === "admin" ? (
							<StatusMessage tone="warning" title={t("adminWarningTitle")}>
								{t("adminWarning")}
							</StatusMessage>
						) : null}
					</div>
				</Section>

				<Section title={t("profile")} description={t("profileDescription")}>
					<FieldGroup>
						<FormField id="user-display-name" label={t("displayName")} error={errors.displayName}>
							<Input
								id="user-display-name"
								autoComplete="off"
								value={values.displayName}
								onChange={(event) => set("displayName", event.target.value)}
								aria-invalid={errors.displayName ? true : undefined}
							/>
						</FormField>
						<FormField id="user-email" label={t("email")} error={errors.email}>
							<Input
								id="user-email"
								type="email"
								inputMode="email"
								autoCapitalize="none"
								autoCorrect="off"
								spellCheck={false}
								autoComplete="off"
								value={values.email}
								onChange={(event) => set("email", event.target.value)}
								aria-invalid={errors.email ? true : undefined}
							/>
						</FormField>
						<Field orientation="horizontal">
							<FieldContent>
								<FieldLabel htmlFor="user-email-verified">{t("emailVerified")}</FieldLabel>
								<FieldDescription>{t("emailVerifiedDescription")}</FieldDescription>
							</FieldContent>
							<Switch
								id="user-email-verified"
								checked={values.emailVerified}
								onCheckedChange={(checked) => set("emailVerified", checked)}
							/>
						</Field>
					</FieldGroup>
				</Section>

				<Section title={t("password")} description={t("passwordDescription")}>
					<FieldGroup>
						<FormField id="user-password" label={t("password")} error={errors.password}>
							<div className="flex gap-2">
								<PasswordInput
									id="user-password"
									className="flex-1"
									autoComplete="new-password"
									value={values.password}
									onChange={(event) => {
										setGenerated(null);
										set("password", event.target.value);
									}}
									aria-invalid={errors.password ? true : undefined}
								/>
								<Button type="button" variant="outline" onClick={generate}>
									<Dices />
									{t("generate")}
								</Button>
							</div>
							<PasswordStrength password={values.password} />
						</FormField>
						{generated && generated === values.password ? (
							<StatusMessage tone="info" title={t("generatedNotice")}>
								<div className="flex flex-col gap-2">
									<span>{t("generatedHint")}</span>
									<CopyField id="user-generated-password" value={generated} />
								</div>
							</StatusMessage>
						) : null}
					</FieldGroup>
				</Section>

				<Section title={t("status")}>
					<Field orientation="horizontal">
						<FieldContent>
							<FieldLabel htmlFor="user-enabled">{t("enabled")}</FieldLabel>
							<FieldDescription>{t("enabledDescription")}</FieldDescription>
						</FieldContent>
						<Switch id="user-enabled" checked={values.enabled} onCheckedChange={(checked) => set("enabled", checked)} />
					</Field>
				</Section>

				<div className="flex flex-col-reverse gap-2 sm:flex-row sm:justify-end">
					<Button asChild variant="outline">
						<Link href="/users">{tCommon("cancel")}</Link>
					</Button>
					<Button type="submit" disabled={submitting}>
						{submitting ? <Spinner /> : null}
						{t("submit")}
					</Button>
				</div>
			</form>
		</Page>
	);
}
